server:
  port: 8080


peanut:
  #server
  server:
    port: 8080


  # WeChat
  wx:
    callback: http://749291su.s7.tunnelfrp.com
    appId: wx6ce73b6ffb0ae646
    secret: 9898baf308136a87bd289726bcd7654d
    token: suxiaowen


  # RocketMq
  rocketmq:
    name-server: 192.168.17.124:9876
    producer:
      group: hello

  # ws
  ws:
    port: 9999

  # Redis
  redis:
    host: 192.168.17.124 
    port: 6379

  #mysql
  mysql:
    ip: 192.168.17.124 
    port: 3306
    db: peanut-chat
    username: root
    password: 345267